from src.document_processor import MarkdownProcessor
from src.prompt_templates import blog_post_template
from src.llm_integration import ContentGenerator

# Step 1: Load all primary knowledge base documents
print("Loading knowledge base...")
processor = MarkdownProcessor("knowledge_base/meridian_wealth/")
docs = processor.process_all()
print(f"  {len(docs)} files loaded: {', '.join(d['filename'] for d in docs)}\n")

# Step 2: Combine into a single context string
kb_context = "\n\n---\n\n".join(
    f"### {doc['filename']}\n{doc['content']}" for doc in docs
)

# Step 3: Build the prompt
topic = "What a fee-only wealth advisory actually does"
prompt = blog_post_template(kb_context, topic)
print(f"Prompt built ({len(prompt)} characters). Sending to OpenAI...\n")

# Step 4: Generate content
generator = ContentGenerator()
blog_post = generator.generate_content(prompt)

# Step 5: Print result
print("=" * 60)
print(blog_post)
print("=" * 60)

# Step 6: Save to file
output_path = "output_sample.md"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(f"<!-- Generated by generate_sample.py | Topic: {topic} -->\n\n")
    f.write(blog_post)

print(f"\nSaved to {output_path}")
